version: "3.5"
services:
  nats-main-n1:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "-c /etc/nats/main-n1.conf"
    networks: [ "smartvillageapp" ]
    volumes:
      - ./config/:/etc/nats
      - ../certs/:/etc/nats/certs
  nats-main-n2:
    image: nats:latest
    ports:
      - "4223:4222"
    command: "-c /etc/nats/main-n2.conf"
    networks: [ "smartvillageapp" ]
    volumes:
      - ./config/:/etc/nats
      - ../certs/:/etc/nats/certs
  nats-main-n3:
    image: nats:latest
    ports:
      - "4224:4222"
    command: "-c /etc/nats/main-n3.conf"
    networks: [ "smartvillageapp" ]
    volumes:
      - ./config/:/etc/nats
      - ../certs/:/etc/nats/certs

networks:
  smartvillageapp:
    name: smartvillageapp