kumuluzee:
  name: user-service
  env:
    name: dev
  version: 1.0.0-SNAPSHOT
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  openapi:
    enabled: true
    ui:
      enabled: true
  security:
    keycloak:
      json: '{
              "realm": "users-realm",
              "bearer-only": true,
              "auth-server-url": "http://localhost:8080/",
              "ssl-required": "external",
              "resource": "users-api",
              "confidential-port": 0
            }'

store-urls:
  keycloak-url: http://keycloak:8080/
  keycloak-realm: users-realm