kumuluzee:
  name: user-service
  env:
    name: dev
  version: 1.0.0-SNAPSHOT
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  openapi:
    enabled: true
    ui:
      enabled: true
  security:
    keycloak:
      json: '{
              "realm": "users-realm",
              "bearer-only": true,
              "auth-server-url": "http://localhost:8080/",
              "ssl-required": "external",
              "resource": "users-api",
              "confidential-port": 0
            }'

#               "auth-server-url": "http://localhost:8180/auth",
#               "auth-server-url": "http://192.168.39.54:31000/auth",

store-urls:
  #  url-catalog: http://localhost:8080/
  #  url-customers: http://localhost:8081/
  #  url-orders: http://localhost:8082/
  #  keycloak-url: http://localhost:8180/auth
  #  keycloak-realm: store
#  url-catalog: http://svc-app-store-catalog-kum:8080/
#  url-customers: http://svc-app-store-customers-kum:8081/
#  url-orders: http://svc-app-store-orders-kum:8082/
  keycloak-url: http://keycloak:8080/
  keycloak-realm: users-realm