kumuluzee:
  name: solar-service
  env:
    name: dev
  version: 1.0.0-SNAPSHOT
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  datasources:
    - jndi-name: jdbc/mainDB
      connection-url: jdbc:postgresql://localhost:26257/smart_village?sslmode=disable
      username: root
      password:
      pool:
        max-size: 10
  openapi:
    enabled: true
    ui:
      enabled: true
#  security:
#    keycloak:
#      json: '{
#              "realm": "users-realm",
#              "bearer-only": true,
#              "auth-server-url": "http://localhost:8080/",
#              "ssl-required": "external",
#              "resource": "users-api",
#              "confidential-port": 0
#            }'

#               "auth-server-url": "http://localhost:8180/auth",
#               "auth-server-url": "http://192.168.39.54:31000/auth",
  nats:
    jetstream: true
    ack-confirmation-timeout: PT5S
    servers:
      - name: secure
        addresses:
          - tls://localhost:4224
        tls:
          trust-store-path: certs\truststore.jks
          trust-store-password: password2
          key-store-path: certs\keystore.jks
          key-store-password: password
        streams:
          - name: solar
            subjects:
              - solar.energy.*
              - solar.sendNewPosition
              - solar.position.*
            #            description:
            #            retention-policy:
            #            max-consumers:
            #            max-bytes:
            #            max-age:
            #            max-msgs:
            #            max-msg-size:
            storage-type: memory
    #            replicas:
    #            no-ack:
    #            template-owner:
    #            discard-policy:
    #            duplicate-window:
    consumer-configuration:
      - name: newMessages
        deliver-policy: new
  #        ack-policy:
  #        replay-policy:
  #        description:
  #        durable:
  #        deliver-subject:
  #        deliver-group:
  #        filter-subject:
  #        sample-frequency:
  #        start-time:
  #        ack-wait:
  #        idle-heartbeat:
  #        max-expires:
  #        inactive-threshold:
  #        start-seq:
  #        max-deliver:
  #        rate-limit:
  #        max-ack-pending:
  #        max-pull-waiting:
  #        max-batch:
  #        max-bytes:
  #        flow-control:
  #        headers-only:
  #        backoff:

store-urls:
  #  url-catalog: http://localhost:8080/
  #  url-customers: http://localhost:8081/
  #  url-orders: http://localhost:8082/
  #  keycloak-url: http://localhost:8180/auth
  #  keycloak-realm: store
#  url-catalog: http://svc-app-store-catalog-kum:8080/
#  url-customers: http://svc-app-store-customers-kum:8081/
#  url-orders: http://svc-app-store-orders-kum:8082/
#  keycloak-url: http://keycloak:8080/
#  keycloak-realm: users-realm